In [41]:
import pandas as pd

In [26]:
pib = pd.read_excel('/Users/guilhermefraga/code/anandxrfeu/schooling_resource_predicter/schooling_resource_predicter_data/raw_data/PIB per capita 2010-2019(2).xlsx')

In [27]:
pib.head(10)

,Regiões / UF,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Rondônia,15320.648230,17491.596257,18938.686787,18007.846558,19462.612886,20678.232093,22078.455002,24098.148559,25554.312462,26497.115337
1,Acre,11384.327529,11990.355872,13360.716600,14777.175686,17034.148330,16954.052764,16841.507185,17204.211322,17636.880111,17722.413717
2,Amazonas,17488.717170,19990.577973,20117.795167,21810.124989,22373.359247,21980.903670,22250.672530,22945.139701,24532.903300,26101.715318
3,Roraima,14713.548783,15871.957378,16424.010519,18461.877096,19608.404922,20256.306320,21416.989731,23160.878980,23188.917393,23593.838382
4,Pará,10874.907102,12838.595549,13741.423509,15210.804208,15430.532294,16011.950552,16694.321514,18553.759507,18952.212240,20734.602196
5,Amapá,12319.322360,13749.969739,15933.060316,17365.381878,17845.344849,18079.656902,18333.410135,19407.648686,20247.532432,20688.210641
6,Tocantins,11857.877420,13095.718819,14590.193606,16098.793109,17495.939985,19094.313475,20604.589331,22002.492583,22933.074856,25021.801741
7,Maranhão,7048.990508,7846.134600,9009.127144,9963.474468,11216.366770,11366.346256,12267.701539,12791.404010,13955.753815,13757.943156
8,Piauí,7139.801870,8260.717478,9060.413770,9824.736842,11808.083417,12218.896260,12893.716023,14091.928984,15432.053655,16124.999788
9,Ceará,9391.072771,10515.146374,11268.149727,12420.756665,14255.054950,14670.161155,15442.628829,16398.446862,17178.256316,17912.169299

In [45]:
pib.to_csv('pib.csv')

In [46]:
pib1 = pd.read_csv('/Users/guilhermefraga/code/anandxrfeu/schooling_resource_predicter/schooling_resource_predicter_data/raw_data/pib.csv')

In [47]:
pib1.columns

Index(['Unnamed: 0', 'Regiões / UF', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019'],
      dtype='object')

In [48]:
pib1 = pib1.drop(columns=['Unnamed: 0'])

In [50]:
pib1.head()

,Regiões / UF,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Rondônia,15320.648230,17491.596257,18938.686787,18007.846558,19462.612886,20678.232093,22078.455002,24098.148559,25554.312462,26497.115337
1,Acre,11384.327529,11990.355872,13360.716600,14777.175686,17034.148330,16954.052764,16841.507185,17204.211322,17636.880111,17722.413717
2,Amazonas,17488.717170,19990.577973,20117.795167,21810.124989,22373.359247,21980.903670,22250.672530,22945.139701,24532.903300,26101.715318
3,Roraima,14713.548783,15871.957378,16424.010519,18461.877096,19608.404922,20256.306320,21416.989731,23160.878980,23188.917393,23593.838382
4,Pará,10874.907102,12838.595549,13741.423509,15210.804208,15430.532294,16011.950552,16694.321514,18553.759507,18952.212240,20734.602196

In [59]:
pib2 = pd.read_excel('/Users/guilhermefraga/code/anandxrfeu/schooling_resource_predicter/schooling_resource_predicter_data/raw_data/PIB 2001-2009.xls')

In [61]:
pib2.to_csv('pib2.csv')

In [62]:
pib2 = pd.read_csv('/Users/guilhermefraga/code/anandxrfeu/schooling_resource_predicter/schooling_resource_predicter_data/raw_data/pib2.csv')

In [63]:
pib2.head(10)

,Unnamed: 0,Regioes / UF,2001,2002,2003,2004,2005,2006,2007,2008,2009
0,0,Rondonia,4651.54,5433.73,6697.39,7608.70,8395.79,8389.27,9435.52,11976.57,13455.71
1,1,Acre,4309.39,4887.09,5502.38,6415.31,6693.55,7040.88,8188.96,9896.16,10686.87
2,2,Amazonas,6223.80,7357.39,8240.36,9778.20,10318.33,11826.14,12399.59,14014.13,14620.99
3,3,Roraima,6028.53,6667.26,7660.32,7645.01,8124.56,9074.44,10038.02,11844.72,13270.54
4,4,Para,3519.78,3975.88,4525.42,5311.11,5612.31,6240.06,6829.34,7992.71,7859.17
5,5,Amapa,5618.06,6372.59,6421.04,6953.76,7335.06,8542.82,9459.06,11032.67,11816.64
6,6,Tocantins,4087.64,4645.51,5886.21,6605.05,6939.47,7208.33,8164.07,10222.71,11277.60
7,7,Maranhao,2341.82,2662.07,3146.82,3634.80,4150.94,4627.71,5044.77,6103.52,6259.46
8,8,Piaui,2252.94,2561.98,3002.04,3328.69,3701.24,4211.90,4611.30,5372.40,6051.41
9,9,Ceara,3250.37,3775.04,4197.42,4689.13,5055.43,5634.94,6037.94,7111.85,7686.67

In [65]:
pib2 = pib2.drop(columns=['Unnamed: 0'])

In [67]:
pib2.head(30)

,Regioes / UF,2001,2002,2003,2004,2005,2006,2007,2008,2009
0,Rondonia,4651.54,5433.73,6697.39,7608.70,8395.79,8389.27,9435.52,11976.57,13455.71
1,Acre,4309.39,4887.09,5502.38,6415.31,6693.55,7040.88,8188.96,9896.16,10686.87
2,Amazonas,6223.80,7357.39,8240.36,9778.20,10318.33,11826.14,12399.59,14014.13,14620.99
3,Roraima,6028.53,6667.26,7660.32,7645.01,8124.56,9074.44,10038.02,11844.72,13270.54
4,Para,3519.78,3975.88,4525.42,5311.11,5612.31,6240.06,6829.34,7992.71,7859.17
5,Amapa,5618.06,6372.59,6421.04,6953.76,7335.06,8542.82,9459.06,11032.67,11816.64
6,Tocantins,4087.64,4645.51,5886.21,6605.05,6939.47,7208.33,8164.07,10222.71,11277.60
7,Maranhao,2341.82,2662.07,3146.82,3634.80,4150.94,4627.71,5044.77,6103.52,6259.46
8,Piaui,2252.94,2561.98,3002.04,3328.69,3701.24,4211.90,4611.30,5372.40,6051.41
9,Ceara,3250.37,3775.04,4197.42,4689.13,5055.43,5634.94,6037.94,7111.85,7686.67
10,Rio grande do Norte,3674.12,4275.64,4679.60,5329.77,5950.48,6753.08,7433.45,8202.81,8893.61
11,Paraiba,3127.70,3557.66,4023.70,4241.02,4691.14,5506.55,6082.37,6865.98,7617.76
12,Pernambuco,3776.73,4360.25,4816.13,5341.88,5933.46,6526.63,7246.73,8064.95,8901.87
13,Alagoas,2971.45,3398.20,3841.93,4373.05,4688.27,5162.19,5767.56,6227.50,6728.22
14,Sergipe,4412.50,5121.47,5800.63,6393.60,6823.52,7559.23,8308.96,9778.96,9786.89
15,Bahia,3866.75,4553.87,5070.25,5835.26,6581.08,6918.98,7785.69,8378.31,9364.62
16,Minas Gerais,6140.84,6966.05,8021.35,9451.07,10013.77,11024.75,12236.40,14232.73,14328.33
17,Espirito Santo,7712.61,8356.79,9557.46,12192.48,13854.93,15234.78,17143.40,20230.85,19145.74
18,Rio de Janeiro,10447.39,11638.58,12636.14,14830.06,16057.38,17692.59,18856.12,21621.36,22103.04
19,São Paulo,12316.67,13404.04,14979.51,16399.03,17975.60,19550.35,21668.43,24456.84,26202.18
20,Parana,7881.91,9023.00,11048.85,12224.52,12344.46,13151.95,15371.28,16927.32,17779.14
21,Santa Catarina,8946.76,10082.26,11922.00,13609.94,14542.74,15633.12,17295.19,20368.53,21214.59
22,Rio grande do Sul,8953.43,10134.75,11849.60,12986.65,13298.13,14304.83,15939.53,18377.73,19778.55
23,Mato Grosso do Sul,6229.87,7079.04,8883.09,9599.19,9561.03,10592.38,12062.84,14187.47,15406.62
24,Mato Grosso,6369.74,8039.65,10518.81,13700.89,13365.07,12340.68,14667.83,18049.81,19087.09
25,Goias,5846.72,7181.07,8072.55,8888.92,8992.02,9956.28,11164.88,12877.88,14446.66
26,Distrito Federal,24564.76,26161.33,28817.76,31663.53,34514.72,37599.28,41061.74,45977.56,50438.48
27,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
pib1.head(30)

,Regiões / UF,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Rondônia,15320.648230,17491.596257,18938.686787,18007.846558,19462.612886,20678.232093,22078.455002,24098.148559,25554.312462,26497.115337
1,Acre,11384.327529,11990.355872,13360.716600,14777.175686,17034.148330,16954.052764,16841.507185,17204.211322,17636.880111,17722.413717
2,Amazonas,17488.717170,19990.577973,20117.795167,21810.124989,22373.359247,21980.903670,22250.672530,22945.139701,24532.903300,26101.715318
3,Roraima,14713.548783,15871.957378,16424.010519,18461.877096,19608.404922,20256.306320,21416.989731,23160.878980,23188.917393,23593.838382
4,Pará,10874.907102,12838.595549,13741.423509,15210.804208,15430.532294,16011.950552,16694.321514,18553.759507,18952.212240,20734.602196
5,Amapá,12319.322360,13749.969739,15933.060316,17365.381878,17845.344849,18079.656902,18333.410135,19407.648686,20247.532432,20688.210641
6,Tocantins,11857.877420,13095.718819,14590.193606,16098.793109,17495.939985,19094.313475,20604.589331,22002.492583,22933.074856,25021.801741
7,Maranhão,7048.990508,7846.134600,9009.127144,9963.474468,11216.366770,11366.346256,12267.701539,12791.404010,13955.753815,13757.943156
8,Piauí,7139.801870,8260.717478,9060.413770,9824.736842,11808.083417,12218.896260,12893.716023,14091.928984,15432.053655,16124.999788
9,Ceará,9391.072771,10515.146374,11268.149727,12420.756665,14255.054950,14670.161155,15442.628829,16398.446862,17178.256316,17912.169299
10,Rio Grande do Norte,11421.396250,12815.667613,14377.125676,15269.437641,15849.325340,16632.177862,17173.359194,18336.452822,19249.603192,20342.107345
11,Paraíba,8899.381203,9787.932860,11136.682786,11847.805661,13422.420550,14133.694676,14778.356683,15500.155637,16107.509022,16919.841893
12,Pernambuco,11049.273181,12426.703562,14330.829927,15328.173469,16722.053573,16796.229192,17783.109046,19170.738037,19623.652685,20702.302878
13,Alagoas,8693.917327,10071.095588,10946.360438,11294.535979,12335.437864,13878.525693,14727.384883,15655.757703,16375.562523,17667.791827
14,Sergipe,12768.132212,13928.609059,15563.832683,16093.545397,16882.713305,17190.197701,17158.530679,17792.579643,18442.625526,19441.232282
15,Bahia,11013.108174,11817.869487,12879.586463,13616.219630,14803.945121,16117.124006,16936.985070,17512.790798,19324.035794,19716.213390
16,Minas Gerais,17918.748704,20281.349848,22275.267413,23697.201321,24917.120051,24885.174170,25946.370359,27291.108322,29223.216446,30794.044136
17,Espírito Santo,24286.436236,29877.242440,32657.460171,30545.237662,33148.560326,30628.169421,27496.918636,28234.533192,34493.119724,34177.048370
18,Rio de Janeiro,28127.412169,31823.878363,35418.153256,38378.593659,40767.255426,39827.069244,38494.912264,40170.311355,44222.658262,45174.080047
19,São Paulo,31384.925988,34546.046160,37207.352934,39282.965812,42197.870497,43694.944562,45559.130613,47028.893159,48542.239755,51140.823938
20,Paraná,21572.209006,24459.068904,27001.967962,30323.456556,31410.744031,33768.898486,35739.942329,37231.860371,38772.741699,40788.769490
21,Santa Catarina,24597.412698,27555.300578,30046.382403,32334.041110,36055.899300,36526.279848,37153.997448,39603.465280,42149.295872,45118.412074
22,Rio Grande do Sul,22556.069572,24695.395083,26701.106584,29764.550896,31927.159435,33961.019917,36219.335317,37381.786840,40362.745002,42406.086175
23,Mato Grosso do Sul,19299.336595,22253.169654,24754.899183,26747.586457,30137.583929,31337.303072,34257.666556,35529.381105,38925.853858,38482.830217
24,Mato Grosso,18655.610836,22482.248246,25572.102381,28035.748129,31396.808812,32895.047974,37476.670331,37926.215888,39931.125130,40787.319481
25,Goiás,17783.029521,19947.769447,22543.934233,23515.549637,25296.597060,26265.440767,27145.092529,28316.087493,28272.962294,29732.397612
26,Distrito Federal,56252.900098,59221.866819,61959.355777,63054.407002,69216.798695,73970.990706,79114.194204,80515.465769,85661.393656,90742.750388

In [69]:
# Obtém o índice da última linha
indice_ultima_linha = pib2.index[-1]

# Remove a última linha usando o método .drop()
pib2_updated = pib2.drop(indice_ultima_linha)

# Exibe o DataFrame resultante sem a última linha
print(pib2_updated)

           Regioes / UF      2001      2002      2003      2004      2005  \
0              Rondonia   4651.54   5433.73   6697.39   7608.70   8395.79
1                  Acre   4309.39   4887.09   5502.38   6415.31   6693.55
2              Amazonas   6223.80   7357.39   8240.36   9778.20  10318.33
3               Roraima   6028.53   6667.26   7660.32   7645.01   8124.56
4                  Para   3519.78   3975.88   4525.42   5311.11   5612.31
5                 Amapa   5618.06   6372.59   6421.04   6953.76   7335.06
6             Tocantins   4087.64   4645.51   5886.21   6605.05   6939.47
7              Maranhao   2341.82   2662.07   3146.82   3634.80   4150.94
8                 Piaui   2252.94   2561.98   3002.04   3328.69   3701.24
9                 Ceara   3250.37   3775.04   4197.42   4689.13   5055.43
10  Rio grande do Norte   3674.12   4275.64   4679.60   5329.77   5950.48
11              Paraiba   3127.70   3557.66   4023.70   4241.02   4691.14
12           Pernambuco   3776.73   4360.25   4816.13   5341.88   5933.46
13              Alagoas   2971.45   3398.20   3841.93   4373.05   4688.27
14              Sergipe   4412.50   5121.47   5800.63   6393.60   6823.52
15                Bahia   3866.75   4553.87   5070.25   5835.26   6581.08
16         Minas Gerais   6140.84   6966.05   8021.35   9451.07  10013.77
17       Espirito Santo   7712.61   8356.79   9557.46  12192.48  13854.93
18       Rio de Janeiro  10447.39  11638.58  12636.14  14830.06  16057.38
19            São Paulo  12316.67  13404.04  14979.51  16399.03  17975.60
20               Parana   7881.91   9023.00  11048.85  12224.52  12344.46
21       Santa Catarina   8946.76  10082.26  11922.00  13609.94  14542.74
22    Rio grande do Sul   8953.43  10134.75  11849.60  12986.65  13298.13
23   Mato Grosso do Sul   6229.87   7079.04   8883.09   9599.19   9561.03
24          Mato Grosso   6369.74   8039.65  10518.81  13700.89  13365.07
25                Goias   5846.72   7181.07   8072.55   8888.92   8992.02
26     Distrito Federal  24564.76  26161.33  28817.76  31663.53  34514.72

        2006      2007      2008      2009
0    8389.27   9435.52  11976.57  13455.71
1    7040.88   8188.96   9896.16  10686.87
2   11826.14  12399.59  14014.13  14620.99
3    9074.44  10038.02  11844.72  13270.54
4    6240.06   6829.34   7992.71   7859.17
5    8542.82   9459.06  11032.67  11816.64
6    7208.33   8164.07  10222.71  11277.60
7    4627.71   5044.77   6103.52   6259.46
8    4211.90   4611.30   5372.40   6051.41
9    5634.94   6037.94   7111.85   7686.67
10   6753.08   7433.45   8202.81   8893.61
11   5506.55   6082.37   6865.98   7617.76
12   6526.63   7246.73   8064.95   8901.87
13   5162.19   5767.56   6227.50   6728.22
14   7559.23   8308.96   9778.96   9786.89
15   6918.98   7785.69   8378.31   9364.62
16  11024.75  12236.40  14232.73  14328.33
17  15234.78  17143.40  20230.85  19145.74
18  17692.59  18856.12  21621.36  22103.04
19  19550.35  21668.43  24456.84  26202.18
20  13151.95  15371.28  16927.32  17779.14
21  15633.12  17295.19  20368.53  21214.59
22  14304.83  15939.53  18377.73  19778.55
23  10592.38  12062.84  14187.47  15406.62
24  12340.68  14667.83  18049.81  19087.09
25   9956.28  11164.88  12877.88  14446.66
26  37599.28  41061.74  45977.56  50438.48

In [70]:
pib2_updated['Regioes / UF'] = pib1['Regiões / UF']

In [71]:
pib2_updated

,Regioes / UF,2001,2002,2003,2004,2005,2006,2007,2008,2009
0,Rondônia,4651.54,5433.73,6697.39,7608.70,8395.79,8389.27,9435.52,11976.57,13455.71
1,Acre,4309.39,4887.09,5502.38,6415.31,6693.55,7040.88,8188.96,9896.16,10686.87
2,Amazonas,6223.80,7357.39,8240.36,9778.20,10318.33,11826.14,12399.59,14014.13,14620.99
3,Roraima,6028.53,6667.26,7660.32,7645.01,8124.56,9074.44,10038.02,11844.72,13270.54
4,Pará,3519.78,3975.88,4525.42,5311.11,5612.31,6240.06,6829.34,7992.71,7859.17
5,Amapá,5618.06,6372.59,6421.04,6953.76,7335.06,8542.82,9459.06,11032.67,11816.64
6,Tocantins,4087.64,4645.51,5886.21,6605.05,6939.47,7208.33,8164.07,10222.71,11277.60
7,Maranhão,2341.82,2662.07,3146.82,3634.80,4150.94,4627.71,5044.77,6103.52,6259.46
8,Piauí,2252.94,2561.98,3002.04,3328.69,3701.24,4211.90,4611.30,5372.40,6051.41
9,Ceará,3250.37,3775.04,4197.42,4689.13,5055.43,5634.94,6037.94,7111.85,7686.67
10,Rio Grande do Norte,3674.12,4275.64,4679.60,5329.77,5950.48,6753.08,7433.45,8202.81,8893.61
11,Paraíba,3127.70,3557.66,4023.70,4241.02,4691.14,5506.55,6082.37,6865.98,7617.76
12,Pernambuco,3776.73,4360.25,4816.13,5341.88,5933.46,6526.63,7246.73,8064.95,8901.87
13,Alagoas,2971.45,3398.20,3841.93,4373.05,4688.27,5162.19,5767.56,6227.50,6728.22
14,Sergipe,4412.50,5121.47,5800.63,6393.60,6823.52,7559.23,8308.96,9778.96,9786.89
15,Bahia,3866.75,4553.87,5070.25,5835.26,6581.08,6918.98,7785.69,8378.31,9364.62
16,Minas Gerais,6140.84,6966.05,8021.35,9451.07,10013.77,11024.75,12236.40,14232.73,14328.33
17,Espírito Santo,7712.61,8356.79,9557.46,12192.48,13854.93,15234.78,17143.40,20230.85,19145.74
18,Rio de Janeiro,10447.39,11638.58,12636.14,14830.06,16057.38,17692.59,18856.12,21621.36,22103.04
19,São Paulo,12316.67,13404.04,14979.51,16399.03,17975.60,19550.35,21668.43,24456.84,26202.18
20,Paraná,7881.91,9023.00,11048.85,12224.52,12344.46,13151.95,15371.28,16927.32,17779.14
21,Santa Catarina,8946.76,10082.26,11922.00,13609.94,14542.74,15633.12,17295.19,20368.53,21214.59
22,Rio Grande do Sul,8953.43,10134.75,11849.60,12986.65,13298.13,14304.83,15939.53,18377.73,19778.55
23,Mato Grosso do Sul,6229.87,7079.04,8883.09,9599.19,9561.03,10592.38,12062.84,14187.47,15406.62
24,Mato Grosso,6369.74,8039.65,10518.81,13700.89,13365.07,12340.68,14667.83,18049.81,19087.09
25,Goiás,5846.72,7181.07,8072.55,8888.92,8992.02,9956.28,11164.88,12877.88,14446.66
26,Distrito Federal,24564.76,26161.33,28817.76,31663.53,34514.72,37599.28,41061.74,45977.56,50438.48

In [74]:
pib1 = pib1.drop(columns=['Regiões / UF'])

In [75]:
pib1

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,15320.648230,17491.596257,18938.686787,18007.846558,19462.612886,20678.232093,22078.455002,24098.148559,25554.312462,26497.115337
1,11384.327529,11990.355872,13360.716600,14777.175686,17034.148330,16954.052764,16841.507185,17204.211322,17636.880111,17722.413717
2,17488.717170,19990.577973,20117.795167,21810.124989,22373.359247,21980.903670,22250.672530,22945.139701,24532.903300,26101.715318
3,14713.548783,15871.957378,16424.010519,18461.877096,19608.404922,20256.306320,21416.989731,23160.878980,23188.917393,23593.838382
4,10874.907102,12838.595549,13741.423509,15210.804208,15430.532294,16011.950552,16694.321514,18553.759507,18952.212240,20734.602196
5,12319.322360,13749.969739,15933.060316,17365.381878,17845.344849,18079.656902,18333.410135,19407.648686,20247.532432,20688.210641
6,11857.877420,13095.718819,14590.193606,16098.793109,17495.939985,19094.313475,20604.589331,22002.492583,22933.074856,25021.801741
7,7048.990508,7846.134600,9009.127144,9963.474468,11216.366770,11366.346256,12267.701539,12791.404010,13955.753815,13757.943156
8,7139.801870,8260.717478,9060.413770,9824.736842,11808.083417,12218.896260,12893.716023,14091.928984,15432.053655,16124.999788
9,9391.072771,10515.146374,11268.149727,12420.756665,14255.054950,14670.161155,15442.628829,16398.446862,17178.256316,17912.169299
10,11421.396250,12815.667613,14377.125676,15269.437641,15849.325340,16632.177862,17173.359194,18336.452822,19249.603192,20342.107345
11,8899.381203,9787.932860,11136.682786,11847.805661,13422.420550,14133.694676,14778.356683,15500.155637,16107.509022,16919.841893
12,11049.273181,12426.703562,14330.829927,15328.173469,16722.053573,16796.229192,17783.109046,19170.738037,19623.652685,20702.302878
13,8693.917327,10071.095588,10946.360438,11294.535979,12335.437864,13878.525693,14727.384883,15655.757703,16375.562523,17667.791827
14,12768.132212,13928.609059,15563.832683,16093.545397,16882.713305,17190.197701,17158.530679,17792.579643,18442.625526,19441.232282
15,11013.108174,11817.869487,12879.586463,13616.219630,14803.945121,16117.124006,16936.985070,17512.790798,19324.035794,19716.213390
16,17918.748704,20281.349848,22275.267413,23697.201321,24917.120051,24885.174170,25946.370359,27291.108322,29223.216446,30794.044136
17,24286.436236,29877.242440,32657.460171,30545.237662,33148.560326,30628.169421,27496.918636,28234.533192,34493.119724,34177.048370
18,28127.412169,31823.878363,35418.153256,38378.593659,40767.255426,39827.069244,38494.912264,40170.311355,44222.658262,45174.080047
19,31384.925988,34546.046160,37207.352934,39282.965812,42197.870497,43694.944562,45559.130613,47028.893159,48542.239755,51140.823938
20,21572.209006,24459.068904,27001.967962,30323.456556,31410.744031,33768.898486,35739.942329,37231.860371,38772.741699,40788.769490
21,24597.412698,27555.300578,30046.382403,32334.041110,36055.899300,36526.279848,37153.997448,39603.465280,42149.295872,45118.412074
22,22556.069572,24695.395083,26701.106584,29764.550896,31927.159435,33961.019917,36219.335317,37381.786840,40362.745002,42406.086175
23,19299.336595,22253.169654,24754.899183,26747.586457,30137.583929,31337.303072,34257.666556,35529.381105,38925.853858,38482.830217
24,18655.610836,22482.248246,25572.102381,28035.748129,31396.808812,32895.047974,37476.670331,37926.215888,39931.125130,40787.319481
25,17783.029521,19947.769447,22543.934233,23515.549637,25296.597060,26265.440767,27145.092529,28316.087493,28272.962294,29732.397612
26,56252.900098,59221.866819,61959.355777,63054.407002,69216.798695,73970.990706,79114.194204,80515.465769,85661.393656,90742.750388

In [84]:
pib3 = pd.concat([pib2_updated, pib])

In [85]:
pib3.head(20)

,Regioes / UF,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Rondônia,4651.54,5433.73,6697.39,7608.70,8395.79,8389.27,9435.52,11976.57,13455.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Acre,4309.39,4887.09,5502.38,6415.31,6693.55,7040.88,8188.96,9896.16,10686.87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Amazonas,6223.80,7357.39,8240.36,9778.20,10318.33,11826.14,12399.59,14014.13,14620.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Roraima,6028.53,6667.26,7660.32,7645.01,8124.56,9074.44,10038.02,11844.72,13270.54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pará,3519.78,3975.88,4525.42,5311.11,5612.31,6240.06,6829.34,7992.71,7859.17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Amapá,5618.06,6372.59,6421.04,6953.76,7335.06,8542.82,9459.06,11032.67,11816.64,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Tocantins,4087.64,4645.51,5886.21,6605.05,6939.47,7208.33,8164.07,10222.71,11277.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Maranhão,2341.82,2662.07,3146.82,3634.80,4150.94,4627.71,5044.77,6103.52,6259.46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Piauí,2252.94,2561.98,3002.04,3328.69,3701.24,4211.90,4611.30,5372.40,6051.41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Ceará,3250.37,3775.04,4197.42,4689.13,5055.43,5634.94,6037.94,7111.85,7686.67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Rio Grande do Norte,3674.12,4275.64,4679.60,5329.77,5950.48,6753.08,7433.45,8202.81,8893.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Paraíba,3127.70,3557.66,4023.70,4241.02,4691.14,5506.55,6082.37,6865.98,7617.76,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Pernambuco,3776.73,4360.25,4816.13,5341.88,5933.46,6526.63,7246.73,8064.95,8901.87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Alagoas,2971.45,3398.20,3841.93,4373.05,4688.27,5162.19,5767.56,6227.50,6728.22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Sergipe,4412.50,5121.47,5800.63,6393.60,6823.52,7559.23,8308.96,9778.96,9786.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Bahia,3866.75,4553.87,5070.25,5835.26,6581.08,6918.98,7785.69,8378.31,9364.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Minas Gerais,6140.84,6966.05,8021.35,9451.07,10013.77,11024.75,12236.40,14232.73,14328.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Espírito Santo,7712.61,8356.79,9557.46,12192.48,13854.93,15234.78,17143.40,20230.85,19145.74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Rio de Janeiro,10447.39,11638.58,12636.14,14830.06,16057.38,17692.59,18856.12,21621.36,22103.04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,São Paulo,12316.67,13404.04,14979.51,16399.03,17975.60,19550.35,21668.43,24456.84,26202.18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
# Remove os anos em comum do pib2_updated para evitar duplicações:
anos_comuns = pib1.columns.intersection(pib2_updated.columns)
pib2_updated = pib2_updated.drop(columns=anos_comuns)

# Concatena os DataFrames horizontalmente:
df_final = pd.concat([pib2_updated, pib1], axis=1)

# Exibe o DataFrame final:
print(df_final)

           Regioes / UF      2001      2002      2003      2004      2005  \
0              Rondônia   4651.54   5433.73   6697.39   7608.70   8395.79
1                  Acre   4309.39   4887.09   5502.38   6415.31   6693.55
2              Amazonas   6223.80   7357.39   8240.36   9778.20  10318.33
3               Roraima   6028.53   6667.26   7660.32   7645.01   8124.56
4                  Pará   3519.78   3975.88   4525.42   5311.11   5612.31
5                 Amapá   5618.06   6372.59   6421.04   6953.76   7335.06
6             Tocantins   4087.64   4645.51   5886.21   6605.05   6939.47
7              Maranhão   2341.82   2662.07   3146.82   3634.80   4150.94
8                 Piauí   2252.94   2561.98   3002.04   3328.69   3701.24
9                 Ceará   3250.37   3775.04   4197.42   4689.13   5055.43
10  Rio Grande do Norte   3674.12   4275.64   4679.60   5329.77   5950.48
11              Paraíba   3127.70   3557.66   4023.70   4241.02   4691.14
12           Pernambuco   3776.73   4360.25   4816.13   5341.88   5933.46
13              Alagoas   2971.45   3398.20   3841.93   4373.05   4688.27
14              Sergipe   4412.50   5121.47   5800.63   6393.60   6823.52
15                Bahia   3866.75   4553.87   5070.25   5835.26   6581.08
16         Minas Gerais   6140.84   6966.05   8021.35   9451.07  10013.77
17       Espírito Santo   7712.61   8356.79   9557.46  12192.48  13854.93
18       Rio de Janeiro  10447.39  11638.58  12636.14  14830.06  16057.38
19            São Paulo  12316.67  13404.04  14979.51  16399.03  17975.60
20               Paraná   7881.91   9023.00  11048.85  12224.52  12344.46
21       Santa Catarina   8946.76  10082.26  11922.00  13609.94  14542.74
22    Rio Grande do Sul   8953.43  10134.75  11849.60  12986.65  13298.13
23   Mato Grosso do Sul   6229.87   7079.04   8883.09   9599.19   9561.03
24          Mato Grosso   6369.74   8039.65  10518.81  13700.89  13365.07
25                Goiás   5846.72   7181.07   8072.55   8888.92   8992.02
26     Distrito Federal  24564.76  26161.33  28817.76  31663.53  34514.72

        2006      2007      2008      2009          2010          2011  \
0    8389.27   9435.52  11976.57  13455.71  15320.648230  17491.596257
1    7040.88   8188.96   9896.16  10686.87  11384.327529  11990.355872
2   11826.14  12399.59  14014.13  14620.99  17488.717170  19990.577973
3    9074.44  10038.02  11844.72  13270.54  14713.548783  15871.957378
4    6240.06   6829.34   7992.71   7859.17  10874.907102  12838.595549
5    8542.82   9459.06  11032.67  11816.64  12319.322360  13749.969739
6    7208.33   8164.07  10222.71  11277.60  11857.877420  13095.718819
7    4627.71   5044.77   6103.52   6259.46   7048.990508   7846.134600
8    4211.90   4611.30   5372.40   6051.41   7139.801870   8260.717478
9    5634.94   6037.94   7111.85   7686.67   9391.072771  10515.146374
10   6753.08   7433.45   8202.81   8893.61  11421.396250  12815.667613
11   5506.55   6082.37   6865.98   7617.76   8899.381203   9787.932860
12   6526.63   7246.73   8064.95   8901.87  11049.273181  12426.703562
13   5162.19   5767.56   6227.50   6728.22   8693.917327  10071.095588
14   7559.23   8308.96   9778.96   9786.89  12768.132212  13928.609059
15   6918.98   7785.69   8378.31   9364.62  11013.108174  11817.869487
16  11024.75  12236.40  14232.73  14328.33  17918.748704  20281.349848
17  15234.78  17143.40  20230.85  19145.74  24286.436236  29877.242440
18  17692.59  18856.12  21621.36  22103.04  28127.412169  31823.878363
19  19550.35  21668.43  24456.84  26202.18  31384.925988  34546.046160
20  13151.95  15371.28  16927.32  17779.14  21572.209006  24459.068904
21  15633.12  17295.19  20368.53  21214.59  24597.412698  27555.300578
22  14304.83  15939.53  18377.73  19778.55  22556.069572  24695.395083
23  10592.38  12062.84  14187.47  15406.62  19299.336595  22253.169654
24  12340.68  14667.83  18049.81  19087.09  18655.610836  22482.248246
25   9956.28  11164.88  12877.88  14446.66  17783.029521  19947.769447
26  37599.28  41061.74  45977.56  50438.48  56252.900098  59221.866819

            2012          2013          2014          2015          2016  \
0   18938.686787  18007.846558  19462.612886  20678.232093  22078.455002
1   13360.716600  14777.175686  17034.148330  16954.052764  16841.507185
2   20117.795167  21810.124989  22373.359247  21980.903670  22250.672530
3   16424.010519  18461.877096  19608.404922  20256.306320  21416.989731
4   13741.423509  15210.804208  15430.532294  16011.950552  16694.321514
5   15933.060316  17365.381878  17845.344849  18079.656902  18333.410135
6   14590.193606  16098.793109  17495.939985  19094.313475  20604.589331
7    9009.127144   9963.474468  11216.366770  11366.346256  12267.701539
8    9060.413770   9824.736842  11808.083417  12218.896260  12893.716023
9   11268.149727  12420.756665  14255.054950  14670.161155  15442.628829
10  14377.125676  15269.437641  15849.325340  16632.177862  17173.359194
11  11136.682786  11847.805661  13422.420550  14133.694676  14778.356683
12  14330.829927  15328.173469  16722.053573  16796.229192  17783.109046
13  10946.360438  11294.535979  12335.437864  13878.525693  14727.384883
14  15563.832683  16093.545397  16882.713305  17190.197701  17158.530679
15  12879.586463  13616.219630  14803.945121  16117.124006  16936.985070
16  22275.267413  23697.201321  24917.120051  24885.174170  25946.370359
17  32657.460171  30545.237662  33148.560326  30628.169421  27496.918636
18  35418.153256  38378.593659  40767.255426  39827.069244  38494.912264
19  37207.352934  39282.965812  42197.870497  43694.944562  45559.130613
20  27001.967962  30323.456556  31410.744031  33768.898486  35739.942329
21  30046.382403  32334.041110  36055.899300  36526.279848  37153.997448
22  26701.106584  29764.550896  31927.159435  33961.019917  36219.335317
23  24754.899183  26747.586457  30137.583929  31337.303072  34257.666556
24  25572.102381  28035.748129  31396.808812  32895.047974  37476.670331
25  22543.934233  23515.549637  25296.597060  26265.440767  27145.092529
26  61959.355777  63054.407002  69216.798695  73970.990706  79114.194204

            2017          2018          2019
0   24098.148559  25554.312462  26497.115337
1   17204.211322  17636.880111  17722.413717
2   22945.139701  24532.903300  26101.715318
3   23160.878980  23188.917393  23593.838382
4   18553.759507  18952.212240  20734.602196
5   19407.648686  20247.532432  20688.210641
6   22002.492583  22933.074856  25021.801741
7   12791.404010  13955.753815  13757.943156
8   14091.928984  15432.053655  16124.999788
9   16398.446862  17178.256316  17912.169299
10  18336.452822  19249.603192  20342.107345
11  15500.155637  16107.509022  16919.841893
12  19170.738037  19623.652685  20702.302878
13  15655.757703  16375.562523  17667.791827
14  17792.579643  18442.625526  19441.232282
15  17512.790798  19324.035794  19716.213390
16  27291.108322  29223.216446  30794.044136
17  28234.533192  34493.119724  34177.048370
18  40170.311355  44222.658262  45174.080047
19  47028.893159  48542.239755  51140.823938
20  37231.860371  38772.741699  40788.769490
21  39603.465280  42149.295872  45118.412074
22  37381.786840  40362.745002  42406.086175
23  35529.381105  38925.853858  38482.830217
24  37926.215888  39931.125130  40787.319481
25  28316.087493  28272.962294  29732.397612
26  80515.465769  85661.393656  90742.750388

In [96]:
df_final.head(30)

,Regioes / UF,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Rondônia,4651.54,5433.73,6697.39,7608.70,8395.79,8389.27,9435.52,11976.57,13455.71,15320.648230,17491.596257,18938.686787,18007.846558,19462.612886,20678.232093,22078.455002,24098.148559,25554.312462,26497.115337
1,Acre,4309.39,4887.09,5502.38,6415.31,6693.55,7040.88,8188.96,9896.16,10686.87,11384.327529,11990.355872,13360.716600,14777.175686,17034.148330,16954.052764,16841.507185,17204.211322,17636.880111,17722.413717
2,Amazonas,6223.80,7357.39,8240.36,9778.20,10318.33,11826.14,12399.59,14014.13,14620.99,17488.717170,19990.577973,20117.795167,21810.124989,22373.359247,21980.903670,22250.672530,22945.139701,24532.903300,26101.715318
3,Roraima,6028.53,6667.26,7660.32,7645.01,8124.56,9074.44,10038.02,11844.72,13270.54,14713.548783,15871.957378,16424.010519,18461.877096,19608.404922,20256.306320,21416.989731,23160.878980,23188.917393,23593.838382
4,Pará,3519.78,3975.88,4525.42,5311.11,5612.31,6240.06,6829.34,7992.71,7859.17,10874.907102,12838.595549,13741.423509,15210.804208,15430.532294,16011.950552,16694.321514,18553.759507,18952.212240,20734.602196
5,Amapá,5618.06,6372.59,6421.04,6953.76,7335.06,8542.82,9459.06,11032.67,11816.64,12319.322360,13749.969739,15933.060316,17365.381878,17845.344849,18079.656902,18333.410135,19407.648686,20247.532432,20688.210641
6,Tocantins,4087.64,4645.51,5886.21,6605.05,6939.47,7208.33,8164.07,10222.71,11277.60,11857.877420,13095.718819,14590.193606,16098.793109,17495.939985,19094.313475,20604.589331,22002.492583,22933.074856,25021.801741
7,Maranhão,2341.82,2662.07,3146.82,3634.80,4150.94,4627.71,5044.77,6103.52,6259.46,7048.990508,7846.134600,9009.127144,9963.474468,11216.366770,11366.346256,12267.701539,12791.404010,13955.753815,13757.943156
8,Piauí,2252.94,2561.98,3002.04,3328.69,3701.24,4211.90,4611.30,5372.40,6051.41,7139.801870,8260.717478,9060.413770,9824.736842,11808.083417,12218.896260,12893.716023,14091.928984,15432.053655,16124.999788
9,Ceará,3250.37,3775.04,4197.42,4689.13,5055.43,5634.94,6037.94,7111.85,7686.67,9391.072771,10515.146374,11268.149727,12420.756665,14255.054950,14670.161155,15442.628829,16398.446862,17178.256316,17912.169299
10,Rio Grande do Norte,3674.12,4275.64,4679.60,5329.77,5950.48,6753.08,7433.45,8202.81,8893.61,11421.396250,12815.667613,14377.125676,15269.437641,15849.325340,16632.177862,17173.359194,18336.452822,19249.603192,20342.107345
11,Paraíba,3127.70,3557.66,4023.70,4241.02,4691.14,5506.55,6082.37,6865.98,7617.76,8899.381203,9787.932860,11136.682786,11847.805661,13422.420550,14133.694676,14778.356683,15500.155637,16107.509022,16919.841893
12,Pernambuco,3776.73,4360.25,4816.13,5341.88,5933.46,6526.63,7246.73,8064.95,8901.87,11049.273181,12426.703562,14330.829927,15328.173469,16722.053573,16796.229192,17783.109046,19170.738037,19623.652685,20702.302878
13,Alagoas,2971.45,3398.20,3841.93,4373.05,4688.27,5162.19,5767.56,6227.50,6728.22,8693.917327,10071.095588,10946.360438,11294.535979,12335.437864,13878.525693,14727.384883,15655.757703,16375.562523,17667.791827
14,Sergipe,4412.50,5121.47,5800.63,6393.60,6823.52,7559.23,8308.96,9778.96,9786.89,12768.132212,13928.609059,15563.832683,16093.545397,16882.713305,17190.197701,17158.530679,17792.579643,18442.625526,19441.232282
15,Bahia,3866.75,4553.87,5070.25,5835.26,6581.08,6918.98,7785.69,8378.31,9364.62,11013.108174,11817.869487,12879.586463,13616.219630,14803.945121,16117.124006,16936.985070,17512.790798,19324.035794,19716.213390
16,Minas Gerais,6140.84,6966.05,8021.35,9451.07,10013.77,11024.75,12236.40,14232.73,14328.33,17918.748704,20281.349848,22275.267413,23697.201321,24917.120051,24885.174170,25946.370359,27291.108322,29223.216446,30794.044136
17,Espírito Santo,7712.61,8356.79,9557.46,12192.48,13854.93,15234.78,17143.40,20230.85,19145.74,24286.436236,29877.242440,32657.460171,30545.237662,33148.560326,30628.169421,27496.918636,28234.533192,34493.119724,34177.048370
18,Rio de Janeiro,10447.39,11638.58,12636.14,14830.06,16057.38,17692.59,18856.12,21621.36,22103.04,28127.412169,31823.878363,35418.153256,38378.593659,40767.255426,39827.069244,38494.912264,40170.311355,44222.658262,45174.080047
19,São Paulo,12316.67,13404.04,14979.51,16399.03,17975.60,19550.35,21668.43,24456.84,26202.18,31384.925988,34546.046160,37207.352934,39282.965812,42197.870497,43694.944562,45559.130613,47028.893159,48542.239755,51140.823938
20,Paraná,7881.91,9023.00,11048.85,12224.52,12344.46,13151.95,15371.28,16927.32,17779.14,21572.209006,24459.068904,27001.967962,30323.456556,31410.744031,33768.898486,35739.942329,37231.860371,38772.741699,40788.769490
21,Santa Catarina,8946.76,10082.26,11922.00,13609.94,14542.74,15633.12,17295.19,20368.53,21214.59,24597.412698,27555.300578,30046.382403,32334.041110,36055.899300,36526.279848,37153.997448,39603.465280,42149.295872,45118.412074
22,Rio Grande do Sul,8953.43,10134.75,11849.60,12986.65,13298.13,14304.83,15939.53,18377.73,19778.55,22556.069572,24695.395083,26701.106584,29764.550896,31927.159435,33961.019917,36219.335317,37381.786840,40362.745002,42406.086175
23,Mato Grosso do Sul,6229.87,7079.04,8883.09,9599.19,9561.03,10592.38,12062.84,14187.47,15406.62,19299.336595,22253.169654,24754.899183,26747.586457,30137.583929,31337.303072,34257.666556,35529.381105,38925.853858,38482.830217
24,Mato Grosso,6369.74,8039.65,10518.81,13700.89,13365.07,12340.68,14667.83,18049.81,19087.09,18655.610836,22482.248246,25572.102381,28035.748129,31396.808812,32895.047974,37476.670331,37926.215888,39931.125130,40787.319481
25,Goiás,5846.72,7181.07,8072.55,8888.92,8992.02,9956.28,11164.88,12877.88,14446.66,17783.029521,19947.769447,22543.934233,23515.549637,25296.597060,26265.440767,27145.092529,28316.087493,28272.962294,29732.397612
26,Distrito Federal,24564.76,26161.33,28817.76,31663.53,34514.72,37599.28,41061.74,45977.56,50438.48,56252.900098,59221.866819,61959.355777,63054.407002,69216.798695,73970.990706,79114.194204,80515.465769,85661.393656,90742.750388

In [98]:
df_final.to_csv('pib2001-2019.csv')