In [1]:
import pandas as pd

### All School Data

In [5]:
pd.read_csv("../transformed_data/school_infrastructure_and_performance.csv")

,Ano,Código_IBGE,Localização,Aprovação,Reprovação,Abandono,Matrículas,Docentes,Estabelecimentos,Turmas
0,2008,1100015,Rural,--,--,--,0,-,0,0
1,2008,1100023,Rural,--,--,--,0,-,0,0
2,2008,1100049,Rural,--,--,--,0,-,0,0
3,2008,1100056,Rural,--,--,--,0,-,0,0
4,2008,1100064,Rural,77.7,22,0.3,328,30,1,11
...,...,...,...,...,...,...,...,...,...,...
167045,2010,3500600,Rural,NaN,NaN,NaN,0,0,0,0
167046,2010,3501202,Rural,NaN,NaN,NaN,0,0,0,0
167047,2010,3501301,Rural,NaN,NaN,NaN,0,0,0,0
167048,2010,3501400,Rural,NaN,NaN,NaN,0,0,0,0
167049,2010,4101150,Rural,NaN,NaN,NaN,0,0,0,0

## Population and Funding data

In [8]:
pd.read_csv("../transformed_data/funding_and_population.csv", sep=";")

             Município   Ano  UF  Código IBGE Valor Consolidado Population
0      Abadia de Goiás  2008  GO      5200050        1755502,19       6182
1      Abadia de Goiás  2009  GO      5200050        1880883,04       6301
2      Abadia de Goiás  2010  GO      5200050         2324131,1       6662
3      Abadia de Goiás  2011  GO      5200050        2850424,86       7023
4      Abadia de Goiás  2012  GO      5200050        3758558,91       7164
...                ...   ...  ..          ...               ...        ...
83485           Zortéa  2018  SC      4219853        2963095,17       3328
83486           Zortéa  2019  SC      4219853        3217392,85       3363
83487           Zortéa  2020  SC      4219853        3465151,28       3398
83488           Zortéa  2021  SC      4219853        4360097,88       3432
83489           Zortéa  2022  SC      4219853        5279079,75       3930

[83490 rows x 6 columns]

##  Access to Internet

In [10]:
pd.read_csv("../transformed_data/AcessToInternet.csv", sep=";")

     Ano        Regiao  Acesso a internet %
0   2008       Sudeste                   25
1   2008      Nordeste                    7
2   2008           Sul                   20
3   2008         Norte                    7
4   2008  Centro Oeste                   21
..   ...           ...                  ...
70  2022       Sudeste                   82
71  2022      Nordeste                   78
72  2022           Sul                   81
73  2022         Norte                   76
74  2022  Centro Oeste                   83

[75 rows x 3 columns]

## Malnutrition

In [11]:
pd.read_csv("../transformed_data/cleaned_Desnutricao.csv", sep=";")
# names to be corrected

,Ano,Região,CODIGO UF,UF,Municipio,Magreza Acentuada,Magreza Acentuada %,Magreza,Magreza %,Eutrofia,Eutofia %,Sobrepeso,Soprepeso %,Obesidade,Obesidade %,Obesidade Grave,Obesidade Grave %,Total
0,2008,CENTRO-OESTE,53,DF,BRASILIA,107.0,1.69%,229.0,3.62%,4.9,77.56%,818.0,12.95%,210.0,3.32%,54.0,0.85%,6.318
1,2008,CENTRO-OESTE,52,GO,ABADIA DE GOIAS,2.0,2.33%,5.0,5.81%,60.0,69.77%,13.0,15.12%,6.0,6.98%,0.0,-,86.000
2,2008,CENTRO-OESTE,52,GO,ABADIANIA,4.0,1.15%,10.0,2.87%,268.0,76.79%,47.0,13.47%,19.0,5.44%,1.0,0.29%,349.000
3,2008,CENTRO-OESTE,52,GO,ACREUNA,0.0,-,1.0,0.97%,81.0,78.64%,15.0,14.56%,6.0,5.83%,0.0,-,103.000
4,2008,CENTRO-OESTE,52,GO,ADELANDIA,0.0,-,1.0,1.23%,70.0,86.42%,7.0,8.64%,3.0,3.7%,0.0,-,81.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89114,2023,SUL,42,SC,WITMARSUM,1.0,0.52%,2.0,1.04%,124.0,64.58%,42.0,21.88%,17.0,8.85%,6.0,3.13%,192.000
89115,2023,SUL,42,SC,XANXERE,5.0,0.41%,18.0,1.49%,733.0,60.83%,255.0,21.16%,155.0,12.86%,39.0,3.24%,1.205
89116,2023,SUL,42,SC,XAVANTINA,0.0,-,1.0,0.78%,68.0,53.13%,36.0,28.13%,18.0,14.06%,5.0,3.91%,128.000
89117,2023,SUL,42,SC,XAXIM,6.0,0.61%,20.0,2.05%,574.0,58.81%,208.0,21.31%,130.0,13.32%,38.0,3.89%,976.000
89118,2023,SUL,42,SC,ZORTEA,1.0,0.34%,13.0,4.42%,189.0,64.29%,60.0,20.41%,24.0,8.16%,7.0,2.38%,294.000

## Unemployment

In [13]:
pd.read_csv("../transformed_data/desocupacao_updated.csv", sep=";")
## I think IGBE should be deleted
## pivot years from columns to rows

,UF,Código_UF,Estado,Código_IBGE,Região,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,AC,12,Acre,1200013,Norte,"8,4","8,975","7,7","8,475","10,875","14,125","13,525","14,5","15,075","15,325","11,7"
1,AL,27,Alagoas,2700102,Nordeste,"11,35","10,6","9,625","11,2","14,075","16,675",17,"14,9","18,575","17,75","11,175"
2,AM,13,Amazonas,1300029,Norte,"9,5","9,075","7,725","9,525","13,575","15,675","13,9",14,"15,775","14,975","10,7"
3,AP,16,Amapá,1600055,Norte,"13,225","11,45","10,325","11,025","15,45","17,725","20,175","17,35","14,9","16,625","12,425"
4,BA,29,Bahia,2900108,Nordeste,"11,05","11,15","10,25","12,25","15,85","16,95",17,"17,2","19,825","19,475","15,425"
5,CE,23,Ceará,2300101,Nordeste,"7,7","7,825","7,35","8,825","11,95","12,575","11,3","10,925","13,175","13,425","9,45"
6,DF,53,Distrito Federal,5300108,Centro Oeste,"8,625","9,025","8,95","10,1",12,"13,175","12,725","13,375","14,75","13,95","11,325"
7,ES,32,Espírito Santo,3200102,Sudeste,"7,125","7,125","6,175","7,7","12,225","13,125","11,475","10,975","12,675","11,125","7,925"
8,GO,52,Goiás,5200050,Centro Oeste,"5,375","5,425","5,3","7,3","10,475","10,575","9,225","10,6","12,425","11,25","7,1"
9,MA,21,Maranhão,2100055,Nordeste,"8,05","7,85","6,825","8,575","11,85","14,325","14,4","14,275","15,85","15,825","10,425"
10,MG,31,Minas Gerais,3100104,Sudeste,"6,875","6,6","6,725","8,475","11,075","12,2","10,7","10,05","12,475","11,65","7,15"
11,MS,50,Mato Grosso do Sul,5000203,Centro Oeste,"6,1","4,675","4,1","6,125","7,675","8,475","7,55","7,95","9,95","8,6","5,025"
12,MT,51,Mato Grosso,5100102,Centro Oeste,"5,5","4,425",4,"6,05","9,35","8,95","7,85","7,95","9,725","7,95","4,25"
13,PA,15,Pará,1500107,Norte,"7,375","7,25","7,2","8,8","11,15","11,75","11,125","10,775","10,35","12,575","9,575"
14,PB,25,Paraíba,2500106,Nordeste,"9,175","8,8","8,85","9,5","11,35","11,375","11,075","11,575","14,625","14,775","11,925"
15,PE,26,Pernambuco,2600054,Nordeste,"9,075","8,975","8,15","9,875","14,55","17,65","16,7","15,475","16,825","19,9","14,2"
16,PI,22,Piauí,2200053,Nordeste,"6,9","7,525","6,525","7,55","9,425","12,85","12,775","12,8","12,8","13,55","10,1"
17,PR,41,Paraná,4100103,Sul,"4,95","4,325",4,"5,85","8,225",9,"8,775","8,525","9,375","8,35","5,825"
18,RJ,33,Rio de Janeiro,3300100,Sudeste,"7,525","6,775","6,25","7,6","11,725","14,925","14,95","14,65","17,35","16,9","12,8"
19,RN,24,Rio Grande do Norte,2400109,Nordeste,"11,4","10,675","11,025","11,975","14,15","14,475","13,55","13,075","15,8","14,8","11,625"
20,RO,11,Rondônia,1100015,Norte,"6,35","5,075","4,175","5,575","7,925","8,225","9,05","7,95","10,425","8,95","4,925"
21,RR,14,Roraima,1400027,Norte,"7,55",8,"6,325","8,525","8,8","9,85","12,25","14,925","16,4","12,05","6,125"
22,RS,43,Rio Grande do Sul,4300001,Sul,"4,8","4,8",5,"6,2","8,175","8,4","8,1","8,025","9,1","8,725","6,1"
23,SC,42,Santa Catarina,4200051,Sul,"3,425","3,075","2,875","4,1","6,325","7,1","6,4","6,075","6,125","5,45","3,85"
24,SE,28,Sergipe,2800100,Nordeste,"10,25","10,3","9,225","9,05","13,25","14,3","16,6","15,075","18,4","17,875","12,9"
25,SP,35,São Paulo,3500105,Sudeste,"7,25","7,225","7,125","9,3","12,35","13,4","13,275","12,45","13,875","13,425","9,075"
26,TO,17,Tocantins,1700251,Norte,"7,725","7,525","7,5","8,625","11,45","11,65","10,625","10,825","11,625","13,325","6,4"

## Poverty Rate

In [26]:
pd.read_csv("../transformed_data/Poverty_rate_updated- 2012-2021.csv", sep=";")
## I think IGBE should be deleted

,Estado,Código_UF,UF,Código_IBGE,Região,2021,"Menos_de_US$_5,5_%_2021",2020,"Menos_de_US$_5,5_%_2020",2019,...,2016,"Menos_de_US$_5,5_%_2016",2015,"Menos_de_US$_5,5_%_2015",2014,"Menos_de_US$_5,5_%_2014",2013,"Menos_de_US$_5,5_%_2013",2012,"Menos_de_US$_5,5_%_2012"
0,Rondônia,11,RO,1100015,Norte,1804543,"31,01",1785821000,"19,7","1766528,84",...,"1707229,36","31,23","1687511,45","28,92",1667748,"26,03","1647435,54","29,5","1627700,76","31,61"
1,Acre,12,AC,1200013,Norte,"889723,6","46,91",877688000,"40,09",865422,...,"828222,31","49,05","816053,08","44,95","802573,22","44,62","789861,42","45,34","776990,97","47,72"
2,Amazonas,13,AM,1300029,Norte,"4102887,3","50,76",4043094802,"44,52","3982728,09",...,"3797253,19","51,69","3735648,12","44,59","3667672,79","43,01","3601162,24","44,61","3537272,62","45,92"
3,Roraima,14,RR,1400027,Norte,"581941,97","46,2","562262429,6","39,63","539599,07",...,"467850,18","32,23","456109,29","31,11","445352,75","30,01","436292,22","34,94","426516,32","33,7"
4,Pará,15,PA,1500107,Norte,"8733604,19","46,6",8643835405,"36,98","8557911,18",...,"8289782,18","47,54","8197330,08","44,67","8099278,44","41,89","8002451,71","45,26","7910095,3","45,85"
5,Amapá,16,AP,1600055,Norte,"867901,53","47,25","853412000,3","41,11",837575,...,"788494,75","44,13","771799,67","41,4",755067,"39,12","737553,14","36,66","720702,6","43,15"
6,Tocantins,17,TO,1700251,Norte,"1593903,01","33,11",1576614340,"30,19","1558905,7",...,"1507124,2","35,18","1490517,56","35,02","1472492,2","33,17","1453438,51","37,45","1435656,63","39,51"
7,Maranhão,21,MA,2100055,Nordeste,"7118080,01","57,46",7079510510,"48,33","7038641,83",...,"6919851,96","54,17","6878325,56","52,88","6837804,47","52,4","6798988,63","54,52","6763728,39","55,92"
8,Piauí,22,PI,2200053,Nordeste,"3287590,71","44,65",3279521480,"38,44","3270840,25",...,"3244782,93","45,46","3232880,73","39,72","3224527,17","41,59","3211974,38","42,97","3207098,79","46,35"
9,Ceará,23,CE,2300101,Nordeste,"9231196,27","46,8",9177637583,"40,57","9125074,76",...,"8950696,61","46,78","8890055,31","45,21","8826164,66","44,31","8781485,25","45,11","8715501,93","49,15"
10,Rio Grande do Norte,24,RN,2400109,Nordeste,"3560625,26","43,19",3529115981,"34,22","3506126,75",...,"3420752,69","38,14","3392738,9","35,34",3361449,"37,68","3331025,54","39,21","3299449,89","41,48"
11,Paraíba,25,PB,2500106,Nordeste,"4036967,64","47,41",4016028753,"41,26","3993254,12",...,"3928566,68","43,74","3908669,74","38,78","3886950,49","41,02","3867782,27","44,32","3849564,51","46,15"
12,Pernambuco,26,PE,2600054,Nordeste,"9614636,47","50,98",9556296067,"42,19","9497001,92",...,"9314887,76","43,57","9259719,56","40,66","9189779,63",38,"9129160,17","41,87","9059658,82","46,11"
13,Alagoas,27,AL,2700102,Nordeste,"3358030,01","51,67",3343326770,"43,89","3328862,74",...,"3284243,26","49,58","3269729,36","50,37","3255384,93","47,93","3238013,84","51,34","3220687,1","50,26"
14,Sergipe,28,SE,2800100,Nordeste,"2336955,51","47,66",2318678000,"35,83","2298235,14",...,"2234265,76","42,46","2214453,57","40,6","2193059,28","39,18","2170562,52","43,48","2148848,3","44,93"
15,Bahia,29,BA,2900108,Nordeste,"14951834,48","46,48",14906419191,"37,52","14848737,84",...,"14663570,49","43,93","14599688,98","39,92","14536870,93","38,79","14477354,61","42,58","14409938,91","46,02"
16,Minas Gerais,31,MG,3100104,Sudeste,"21397247,32","23,74",21276016558,"17,06","21151239,91",...,"20761277,19","21,68","20625961,61","19,19","20486394,03","19,15","20339370,95","21,31","20213389,86","23,17"
17,Espírito Santo,32,ES,3200102,Sudeste,"4104539,43","26,29",4059501449,"18,66","4014539,88",...,"3874829,26","23,71","3828265,42","22,18","3780296,78","20,27","3731799,9","21,85","3685249,52","21,39"
18,Rio de Janeiro,33,RJ,3300100,Sudeste,"17460829,74","23,56",17358898414,"20,72","17255865,46",...,"16935873,27","20,35","16830104,2","17,65","16718199,77","16,71","16606616,52","18,84","16496144,04","20,44"
19,São Paulo,35,SP,3500105,Sudeste,"46623127,78","17,48",46269533408,"14,32","45888808,56",...,"44723031,28","13,25","44323502,63","12,37","43908972,83","11,02","43501895,16","12,14","43071215,28","12,42"
20,Paraná,41,PR,4100103,Sul,"11580329,49","17,27",11503028677,"14,9","11418734,94",...,"11159985,99",15,"11073288,01","13,48","10977575,67","11,66","10887402,25","13,75","10800860,61","15,09"
21,Santa Catarina,42,SC,4200051,Sul,"7322533,2","10,49",7239235754,"8,52","7151499,74",...,"6878656,32","10,03","6787412,86","8,57","6695834,29","7,98","6605740,43","9,12","6516794,77","10,39"
22,Rio Grande do Sul,43,RS,4300001,Sul,"11443201,96","13,55",11402952306,"11,97","11356194,22",...,"11205041,65","12,85","11149344,09","11,5","11094238,09","11,88","11039489,62","12,13","10990874,51","14,2"
23,Mato Grosso do Sul,50,MS,5000203,Centro Oeste,"2768103,01","22,42",2739021000,"16,38","2708950,27",...,"2617170,85","17,6","2586681,11","17,86","2554643,32","16,89","2523087,08","18,31","2492409,16","18,8"
24,Mato Grosso,51,MT,5100102,Centro Oeste,"3510273,98","20,59",3467156279,"17,16","3430303,76",...,"3304672,09","19,08",3263522,"16,69",3219155,"16,96","3174019,93","16,49","3135087,66","19,05"
25,Goiás,52,GO,5200050,Centro Oeste,"7206333,39","22,35",7108605670,"18,05","7019294,89",...,"6723531,04","19,27","6624606,24","16,67","6515612,3","15,77","6416433,23","15,19","6311946,56","19,36"
26,Distrito Federal,53,DF,5300108,Centro Oeste,"3090277,16","15,09",3047737760,"12,38","3008173,78",...,"2883848,42","15,16","2840737,19","13,58","2797477,11","13,75","2753720,94","13,75","2715681,54","15,16"

## GDP Data

In [17]:
pd.read_csv("../transformed_data/updated_pib2000-2020.csv", sep=";")
## I think IGBE should be deleted
## pivot years from columns to rows

,Estado,Codigo UF,UF,Código_IBGE,Região,2000,2001,2002,2003,2004,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Acre,12,AC,1200013,Norte,"3864,01","4309,39","4887,09","5502,38","6415,31",...,"11990,35587","13360,7166","14777,17569","17034,14833","16954,05276","16841,50719","17204,21132","17636,88011","17722,41372","18420,26"
1,Alagoas,27,AL,2700102,Nordeste,"2752,32","2971,45","3398,2","3841,93","4373,05",...,"10071,09559","10946,36044","11294,53598","12335,43786","13878,52569","14727,38488","15655,7577","16375,56252","17667,79183","18857,69"
2,Amapá,16,AP,1600055,Norte,"4941,04","5618,06","6372,59","6421,04","6953,76",...,"13749,96974","15933,06032","17365,38188","17845,34485","18079,6569","18333,41014","19407,64869","20247,53243","20688,21064","21431,53"
3,Amazonas,13,AM,1300029,Norte,"5955,35","6223,8","7357,39","8240,36","9778,2",...,"19990,57797","20117,79517","21810,12499","22373,35925","21980,90367","22250,67253","22945,1397","24532,9033","26101,71532","27572,96"
4,Bahia,29,BA,2900108,Nordeste,"3559,47","3866,75","4553,87","5070,25","5835,26",...,"11817,86949","12879,58646","13616,21963","14803,94512","16117,12401","16936,98507","17512,7908","19324,03579","19716,21339","20449,29"
5,Ceará,23,CE,2300101,Nordeste,"3042,41","3250,37","3775,04","4197,42","4689,13",...,"10515,14637","11268,14973","12420,75667","14255,05495","14670,16115","15442,62883","16398,44686","17178,25632","17912,1693","18168,35"
6,Distrito Federal,53,DF,5300108,Centro Oeste,"22658,01","24564,76","26161,33","28817,76","31663,53",...,"59221,86682","61959,35578","63054,407","69216,7987","73970,99071","79114,1942","80515,46577","85661,39366","90742,75039","87016,16"
7,Espírito Santo,32,ES,3200102,Sudeste,"7506,25","7712,61","8356,79","9557,46","12192,48",...,"29877,24244","32657,46017","30545,23766","33148,56033","30628,16942","27496,91864","28234,53319","34493,11972","34177,04837","34065,98"
8,Goiás,52,GO,5200050,Centro Oeste,"5246,42","5846,72","7181,07","8072,55","8888,92",...,"19947,76945","22543,93423","23515,54964","25296,59706","26265,44077","27145,09253","28316,08749","28272,96229","29732,39761","31506,97"
9,Maranhão,21,MA,2100055,Nordeste,"2107,22","2341,82","2662,07","3146,82","3634,8",...,"7846,1346","9009,127144","9963,474468","11216,36677","11366,34626","12267,70154","12791,40401","13955,75381","13757,94316","15027,69"
10,Mato Grosso,51,MT,5100102,Centro Oeste,"5937,87","6369,74","8039,65","10518,81","13700,89",...,"22482,24825","25572,10238","28035,74813","31396,80881","32895,04797","37476,67033","37926,21589","39931,12513","40787,31948","50663,19"
11,Mato Grosso do Sul,50,MS,5000203,Centro Oeste,"5447,73","6229,87","7079,04","8883,09","9599,19",...,"22253,16965","24754,89918","26747,58646","30137,58393","31337,30307","34257,66656","35529,3811","38925,85386","38482,83022","43649,17"
12,Minas Gerais,31,MG,3100104,Sudeste,"5623,47","6140,84","6966,05","8021,35","9451,07",...,"20281,34985","22275,26741","23697,20132","24917,12005","24885,17417","25946,37036","27291,10832","29223,21645","30794,04414","32066,73"
13,Pará,15,PA,1500107,Norte,"3076,43","3519,78","3975,88","4525,42","5311,11",...,"12838,59555","13741,42351","15210,80421","15430,53229","16011,95055","16694,32151","18553,75951","18952,21224","20734,6022","24846,62"
14,Paraíba,25,PB,2500106,Nordeste,"2711,39","3127,7","3557,66","4023,7","4241,02",...,"9787,93286","11136,68279","11847,80566","13422,42055","14133,69468","14778,35668","15500,15564","16107,50902","16919,84189","17402,13"
15,Paraná,41,PR,4100103,Sul,"7228,64","7881,91",9023,"11048,85","12224,52",...,"24459,0689","27001,96796","30323,45656","31410,74403","33768,89849","35739,94233","37231,86037","38772,7417","40788,76949","42366,71"
16,Pernambuco,26,PE,2600054,Nordeste,"3404,64","3776,73","4360,25","4816,13","5341,88",...,"12426,70356","14330,82993","15328,17347","16722,05357","16796,22919","17783,10905","19170,73804","19623,65268","20702,30288","20101,38"
17,Piauí,22,PI,2200053,Nordeste,"2132,3","2252,94","2561,98","3002,04","3328,69",...,"8260,717478","9060,41377","9824,736842","11808,08342","12218,89626","12893,71602","14091,92898","15432,05365","16124,99979","17184,7"
18,Rio de Janeiro,33,RJ,3300100,Sudeste,"9711,07","10447,39","11638,58","12636,14","14830,06",...,"31823,87836","35418,15326","38378,59366","40767,25543","39827,06924","38494,91226","40170,31136","44222,65826","45174,08005","43407,55"
19,Rio Grande do Norte,24,RN,2400109,Nordeste,"3284,31","3674,12","4275,64","4679,6","5329,77",...,"12815,66761","14377,12568","15269,43764","15849,32534","16632,17786","17173,35919","18336,45282","19249,60319","20342,10735","20342,11"
20,Rio Grande do Sul,43,RS,4300001,Sul,"8030,66","8953,43","10134,75","11849,6","12986,65",...,"24695,39508","26701,10658","29764,5509","31927,15943","33961,01992","36219,33532","37381,78684","40362,745","42406,08618","41227,61"
21,Rondônia,11,RO,1100015,Norte,"4309,46","4651,54","5433,73","6697,39","7608,7",...,"17491,59626","18938,68679","18007,84656","19462,61289","20678,23209","22078,455","24098,14856","25554,31246","26497,11534","28722,45"
22,Roraima,14,RR,1400027,Norte,"5476,79","6028,53","6667,26","7660,32","7645,01",...,"15871,95738","16424,01052","18461,8771","19608,40492","20256,30632","21416,98973","23160,87898","23188,91739","23593,83838","25387,77"
23,Santa Catarina,42,SC,4200051,Sul,"8086,07","8946,76","10082,26",11922,"13609,94",...,"27555,30058","30046,3824","32334,04111","36055,8993","36526,27985","37153,99745","39603,46528","42149,29587","45118,41207","48159,24"
24,São Paulo,35,SP,3500105,Sudeste,"11453,79","12316,67","13404,04","14979,51","16399,03",...,"34546,04616","37207,35293","39282,96581","42197,8705","43694,94456","45559,13061","47028,89316","48542,23975","51140,82394","51364,73"
25,Sergipe,28,SE,2800100,Nordeste,"3664,83","4412,5","5121,47","5800,63","6393,6",...,"13928,60906","15563,83268","16093,5454","16882,71331","17190,1977","17158,53068","17792,57964","18442,62553","19441,23228","19583,07"
26,Tocantins,17,TO,1700251,Norte,"3173,22","4087,64","4645,51","5886,21","6605,05",...,"13095,71882","14590,19361","16098,79311","17495,93998","19094,31347","20604,58933","22002,49258","22933,07486","25021,80174","27448,43"

## Brazil municipalities, cities and region mapping

In [25]:
pd.read_csv("../raw_data/Tabela_de_Municipios.csv", sep=";")

,Código_UF,Estado,UF,Código_IBGE,Município,Região
0,11.0,Rondônia,RO,1100015.0,Alta Floresta D'Oeste,Norte
1,11.0,Rondônia,RO,1100023.0,Ariquemes,Norte
2,11.0,Rondônia,RO,1100031.0,Cabixi,Norte
3,11.0,Rondônia,RO,1100049.0,Cacoal,Norte
4,11.0,Rondônia,RO,1100056.0,Cerejeiras,Norte
...,...,...,...,...,...,...
5569,52.0,Goiás,GO,5222203.0,Vila Boa,Centro Oeste
5570,52.0,Goiás,GO,5222302.0,Vila Propício,Centro Oeste
5571,53.0,Distrito Federal,DF,5300108.0,Brasília,Centro Oeste
5572,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,NaN,NaN,NaN,NaN,NaN