# Funding

### Municipality wise Funding 

1 Visit https://www.fnde.gov.br/dadosabertos/dataset/fundeb 

2 Click on Distribution of Fundeb resources. You shoukd now be on site http://sisweb.tesouro.gov.br/apex/f?p=2600:1 

3 Select the following options

    3.1 Transferências > FUNDEB

    3.2 Destinação > todos os municípios

    3.3 Estado > All States

    3.4 Data > All Years and All Months 

4 Click Buscar 

5 Click Exportar

In [11]:
import pandas as pd

In [28]:
df = pd.read_csv("../raw_data/funding/transferências_para_municípios.csv", sep=";",  encoding="ISO-8859-1")
df

,UF,Município,Ano,Transferência,Valor Consolidado,Código IBGE,Código SIAFI
0,AC,Acrelândia,2007,FUNDEB - FPE,"R$2.597.330,67",1200013,643
1,AC,Acrelândia,2007,FUNDEB - FPM,"R$422.278,54",1200013,643
2,AC,Acrelândia,2007,FUNDEB - ICMS,"R$741.574,11",1200013,643
3,AC,Acrelândia,2007,FUNDEB - IPI-EXP,"R$1.027,13",1200013,643
4,AC,Acrelândia,2007,FUNDEB - IPVA,"R$7.611,78",1200013,643
...,...,...,...,...,...,...,...
810996,TO,Xambioá,2023,FUNDEB - ICMS,"R$2.477.662,01",1722107,9643
810997,TO,Xambioá,2023,FUNDEB - IPI-EXP,"R$6.317,04",1722107,9643
810998,TO,Xambioá,2023,FUNDEB - IPVA,"R$198.460,72",1722107,9643
810999,TO,Xambioá,2023,FUNDEB - ITCMD,"R$42.507,33",1722107,9643
811000,TO,Xambioá,2023,FUNDEB - ITR,"R$9.116,06",1722107,9643

In [29]:
#Remove 'R$' and convert 'Valor Consolidado' column to numeric
df['Valor Consolidado'] = df['Valor Consolidado'].str.replace('R$', '', regex=False)
df['Valor Consolidado'] = df['Valor Consolidado'].str.replace('.', '', regex=False)
df['Valor Consolidado'] = df['Valor Consolidado'].str.replace(',', '.', regex=True).astype(float)

In [30]:
df

,UF,Município,Ano,Transferência,Valor Consolidado,Código IBGE,Código SIAFI
0,AC,Acrelândia,2007,FUNDEB - FPE,2597330.67,1200013,643
1,AC,Acrelândia,2007,FUNDEB - FPM,422278.54,1200013,643
2,AC,Acrelândia,2007,FUNDEB - ICMS,741574.11,1200013,643
3,AC,Acrelândia,2007,FUNDEB - IPI-EXP,1027.13,1200013,643
4,AC,Acrelândia,2007,FUNDEB - IPVA,7611.78,1200013,643
...,...,...,...,...,...,...,...
810996,TO,Xambioá,2023,FUNDEB - ICMS,2477662.01,1722107,9643
810997,TO,Xambioá,2023,FUNDEB - IPI-EXP,6317.04,1722107,9643
810998,TO,Xambioá,2023,FUNDEB - IPVA,198460.72,1722107,9643
810999,TO,Xambioá,2023,FUNDEB - ITCMD,42507.33,1722107,9643
811000,TO,Xambioá,2023,FUNDEB - ITR,9116.06,1722107,9643

In [31]:
# Group by 'Município', 'Ano', 'UF' and 'Código IBGE' and sum 'Valor Consolidado'
df_grouped = df.groupby(['Município', 'Ano', 'UF', 'Código IBGE'])['Valor Consolidado'].sum().reset_index()
df_grouped

             Município   Ano  UF  Código IBGE  Valor Consolidado
0      Abadia de Goiás  2007  GO      5200050         1261780.19
1      Abadia de Goiás  2008  GO      5200050         1755502.19
2      Abadia de Goiás  2009  GO      5200050         1880883.04
3      Abadia de Goiás  2010  GO      5200050         2324131.10
4      Abadia de Goiás  2011  GO      5200050         2850424.86
...                ...   ...  ..          ...                ...
94614             Óleo  2019  SP      3533809         1565105.07
94615             Óleo  2020  SP      3533809         1425284.00
94616             Óleo  2021  SP      3533809         1691621.32
94617             Óleo  2022  SP      3533809         1729157.99
94618             Óleo  2023  SP      3533809         1113181.64

[94619 rows x 5 columns]

In [32]:
columns_to_drop = ['Município', 'UF']
df = df_grouped.drop(columns=columns_to_drop)
df

        Ano  Código IBGE  Valor Consolidado
0      2007      5200050         1261780.19
1      2008      5200050         1755502.19
2      2009      5200050         1880883.04
3      2010      5200050         2324131.10
4      2011      5200050         2850424.86
...     ...          ...                ...
94614  2019      3533809         1565105.07
94615  2020      3533809         1425284.00
94616  2021      3533809         1691621.32
94617  2022      3533809         1729157.99
94618  2023      3533809         1113181.64

[94619 rows x 3 columns]

In [34]:
# Export the cleaned and pivoted dataframe to CSV
file_path = "../transformed_data/funding_per_municipality.csv"
df.to_csv(file_path, index=False)